name: Lint and auto-format PRs

permissions:
  contents: write

on: push

jobs:
  lint_and_format:
    name: Lint and auto-format
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      # Checkout previous commit and then pull, to fetch everything in between
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.push.before}}
      - run: |
          git pull origin $GITHUB_REF
          git checkout $GITHUB_REF

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
         node-version: 14
         cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run ESLint
        run: npx gulp lint

      - name: Run Prettier
        run: npx pretty-quick --branch ${{github.event.pull_request.base.sha}}

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add --update
          git commit -m "Auto-format with Prettier" || :
          git push origin HEAD:${{github.ref}}
