name: Run Prettier when merging PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Prettier:
    runs-on: ubuntu-latest

    steps:
      # Checkout previous commit and then pull, to fetch everything in between
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - run: |
          git pull origin ${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
         node-version: '14'
         cache: 'npm'
       
      - name: Install npm dependencies
        run: npm install

      - name: Run Prettier
        run: npx pretty-quick --branch ${{ github.event.pull_request.base.sha }}
        
      - name: Commit and push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add --update
          git commit -m "Auto-format with Prettier" || :
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
